//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUILayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimoReceptor {
            get {
                return ((string)(this["UltimoReceptor"]));
            }
            set {
                this["UltimoReceptor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimaEmpresaTransporte {
            get {
                return ((string)(this["UltimaEmpresaTransporte"]));
            }
            set {
                this["UltimaEmpresaTransporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UsuarioST")]
        public string UsuarioBD {
            get {
                return ((string)(this["UsuarioBD"]));
            }
            set {
                this["UsuarioBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Credomatic")]
        public string PassBD {
            get {
                return ((string)(this["PassBD"]));
            }
            set {
                this["PassBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SISTEMA TESORERIA")]
        public string BaseDatos {
            get {
                return ((string)(this["BaseDatos"]));
            }
            set {
                this["BaseDatos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.120.201.56")]
        public string ServidorBD {
            get {
                return ((string)(this["ServidorBD"]));
            }
            set {
                this["ServidorBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int BaudRate {
            get {
                return ((int)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Impresora {
            get {
                return ((string)(this["Impresora"]));
            }
            set {
                this["Impresora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E7")]
        public string CeldaADenominacionesImportacion {
            get {
                return ((string)(this["CeldaADenominacionesImportacion"]));
            }
            set {
                this["CeldaADenominacionesImportacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O7")]
        public string CeldaBDenominacionesImportacion {
            get {
                return ((string)(this["CeldaBDenominacionesImportacion"]));
            }
            set {
                this["CeldaBDenominacionesImportacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P8")]
        public string CeldaATMsImportacion {
            get {
                return ((string)(this["CeldaATMsImportacion"]));
            }
            set {
                this["CeldaATMsImportacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I4")]
        public string CeldaFechaImportacion {
            get {
                return ((string)(this["CeldaFechaImportacion"]));
            }
            set {
                this["CeldaFechaImportacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q8")]
        public string CeldaTiposATMsImportacion {
            get {
                return ((string)(this["CeldaTiposATMsImportacion"]));
            }
            set {
                this["CeldaTiposATMsImportacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cornsilk")]
        public global::System.Drawing.Color ErrorImportacionCargasATMDesconocido {
            get {
                return ((global::System.Drawing.Color)(this["ErrorImportacionCargasATMDesconocido"]));
            }
            set {
                this["ErrorImportacionCargasATMDesconocido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Turquoise")]
        public global::System.Drawing.Color ErrorImportacionCargasTipoCargaErronea {
            get {
                return ((global::System.Drawing.Color)(this["ErrorImportacionCargasTipoCargaErronea"]));
            }
            set {
                this["ErrorImportacionCargasTipoCargaErronea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color ErrorImportacionCargasCantidadCarga {
            get {
                return ((global::System.Drawing.Color)(this["ErrorImportacionCargasCantidadCarga"]));
            }
            set {
                this["ErrorImportacionCargasCantidadCarga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color ErrorImportacionCargasDenominacionCarga {
            get {
                return ((global::System.Drawing.Color)(this["ErrorImportacionCargasDenominacionCarga"]));
            }
            set {
                this["ErrorImportacionCargasDenominacionCarga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 255")]
        public global::System.Drawing.Color ErrorImportacionCargasNumeroCartuchos {
            get {
                return ((global::System.Drawing.Color)(this["ErrorImportacionCargasNumeroCartuchos"]));
            }
            set {
                this["ErrorImportacionCargasNumeroCartuchos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImpresoraManifiestos {
            get {
                return ((string)(this["ImpresoraManifiestos"]));
            }
            set {
                this["ImpresoraManifiestos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ErrorGeneracionCargasATMDesconocido {
            get {
                return ((global::System.Drawing.Color)(this["ErrorGeneracionCargasATMDesconocido"]));
            }
            set {
                this["ErrorGeneracionCargasATMDesconocido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color ErrorGeneracionCargasMonto {
            get {
                return ((global::System.Drawing.Color)(this["ErrorGeneracionCargasMonto"]));
            }
            set {
                this["ErrorGeneracionCargasMonto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IndianRed")]
        public global::System.Drawing.Color ErrorGeneracionCargasCantidadDenominaciones {
            get {
                return ((global::System.Drawing.Color)(this["ErrorGeneracionCargasCantidadDenominaciones"]));
            }
            set {
                this["ErrorGeneracionCargasCantidadDenominaciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color ErrorGeneracionCargasDenominaciones {
            get {
                return ((global::System.Drawing.Color)(this["ErrorGeneracionCargasDenominaciones"]));
            }
            set {
                this["ErrorGeneracionCargasDenominaciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Khaki")]
        public global::System.Drawing.Color ErrorGeneracionCargasCantidadCartuchos {
            get {
                return ((global::System.Drawing.Color)(this["ErrorGeneracionCargasCantidadCartuchos"]));
            }
            set {
                this["ErrorGeneracionCargasCantidadCartuchos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D5")]
        public string CeldaADenominacionesGeneracion {
            get {
                return ((string)(this["CeldaADenominacionesGeneracion"]));
            }
            set {
                this["CeldaADenominacionesGeneracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G5")]
        public string CeldaBDenominacionesGeneracion {
            get {
                return ((string)(this["CeldaBDenominacionesGeneracion"]));
            }
            set {
                this["CeldaBDenominacionesGeneracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B6")]
        public string CeldaATMsAGeneracion {
            get {
                return ((string)(this["CeldaATMsAGeneracion"]));
            }
            set {
                this["CeldaATMsAGeneracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B3")]
        public string CeldaFechaGeneracion {
            get {
                return ((string)(this["CeldaFechaGeneracion"]));
            }
            set {
                this["CeldaFechaGeneracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M5")]
        public string CeldaCDenominacionesGeneracion {
            get {
                return ((string)(this["CeldaCDenominacionesGeneracion"]));
            }
            set {
                this["CeldaCDenominacionesGeneracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M5")]
        public string CeldaDDenominacionesGeneracion {
            get {
                return ((string)(this["CeldaDDenominacionesGeneracion"]));
            }
            set {
                this["CeldaDDenominacionesGeneracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K6")]
        public string CeldaATMsBGeneracion {
            get {
                return ((string)(this["CeldaATMsBGeneracion"]));
            }
            set {
                this["CeldaATMsBGeneracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 128")]
        public global::System.Drawing.Color ErrorGeneracionCargasBalanceo {
            get {
                return ((global::System.Drawing.Color)(this["ErrorGeneracionCargasBalanceo"]));
            }
            set {
                this["ErrorGeneracionCargasBalanceo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ErrorGeneracionMinimoFormulas {
            get {
                return ((global::System.Drawing.Color)(this["ErrorGeneracionMinimoFormulas"]));
            }
            set {
                this["ErrorGeneracionMinimoFormulas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CRI400A")]
        public string ServidorAS400 {
            get {
                return ((string)(this["ServidorAS400"]));
            }
            set {
                this["ServidorAS400"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.120.131.100")]
        public string IPServidorAutomatizado {
            get {
                return ((string)(this["IPServidorAutomatizado"]));
            }
            set {
                this["IPServidorAutomatizado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8001")]
        public string PuertoServidorAutomatizado {
            get {
                return ((string)(this["PuertoServidorAutomatizado"]));
            }
            set {
                this["PuertoServidorAutomatizado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B3")]
        public string CeldaCarga {
            get {
                return ((string)(this["CeldaCarga"]));
            }
            set {
                this["CeldaCarga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C3")]
        public string CeldaATMCargaAtmRuta {
            get {
                return ((string)(this["CeldaATMCargaAtmRuta"]));
            }
            set {
                this["CeldaATMCargaAtmRuta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D3")]
        public string CeldaRutaCargaATM {
            get {
                return ((string)(this["CeldaRutaCargaATM"]));
            }
            set {
                this["CeldaRutaCargaATM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E3")]
        public string CeldaHoraCargaATM {
            get {
                return ((string)(this["CeldaHoraCargaATM"]));
            }
            set {
                this["CeldaHoraCargaATM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A2")]
        public string CeldaImportacionSucursal {
            get {
                return ((string)(this["CeldaImportacionSucursal"]));
            }
            set {
                this["CeldaImportacionSucursal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C2")]
        public string CeldaSucursalDireccion {
            get {
                return ((string)(this["CeldaSucursalDireccion"]));
            }
            set {
                this["CeldaSucursalDireccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D2")]
        public string CeldaSucursalProvincia {
            get {
                return ((string)(this["CeldaSucursalProvincia"]));
            }
            set {
                this["CeldaSucursalProvincia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public string CeldaSucursalTransportadora {
            get {
                return ((string)(this["CeldaSucursalTransportadora"]));
            }
            set {
                this["CeldaSucursalTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E2")]
        public string CeldaSucursalTipo {
            get {
                return ((string)(this["CeldaSucursalTipo"]));
            }
            set {
                this["CeldaSucursalTipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2")]
        public string CeldaSucursalEntidad {
            get {
                return ((string)(this["CeldaSucursalEntidad"]));
            }
            set {
                this["CeldaSucursalEntidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C5")]
        public string CeldaSucucursalEmergenciaCeldaPDenominacion {
            get {
                return ((string)(this["CeldaSucucursalEmergenciaCeldaPDenominacion"]));
            }
            set {
                this["CeldaSucucursalEmergenciaCeldaPDenominacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D5")]
        public string CeldaSucucursalEmergenciaCeldaSDenominacion {
            get {
                return ((string)(this["CeldaSucucursalEmergenciaCeldaSDenominacion"]));
            }
            set {
                this["CeldaSucucursalEmergenciaCeldaSDenominacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H5")]
        public string CedlaSucursalEmergenciaCeldaTDenominacion {
            get {
                return ((string)(this["CedlaSucursalEmergenciaCeldaTDenominacion"]));
            }
            set {
                this["CedlaSucursalEmergenciaCeldaTDenominacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H5")]
        public string CeldaSucursalEmergenciaCeldaCDenominacion {
            get {
                return ((string)(this["CeldaSucursalEmergenciaCeldaCDenominacion"]));
            }
            set {
                this["CeldaSucursalEmergenciaCeldaCDenominacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6")]
        public string CeldaSucursalEmergenciaATMDolares {
            get {
                return ((string)(this["CeldaSucursalEmergenciaATMDolares"]));
            }
            set {
                this["CeldaSucursalEmergenciaATMDolares"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A6")]
        public string CeldaSucursalEmergenciaColones {
            get {
                return ((string)(this["CeldaSucursalEmergenciaColones"]));
            }
            set {
                this["CeldaSucursalEmergenciaColones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I6")]
        public string CeldaSucursalEmergenciaRuta {
            get {
                return ((string)(this["CeldaSucursalEmergenciaRuta"]));
            }
            set {
                this["CeldaSucursalEmergenciaRuta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public string CeldaTrasnportadoraPlanillas {
            get {
                return ((string)(this["CeldaTrasnportadoraPlanillas"]));
            }
            set {
                this["CeldaTrasnportadoraPlanillas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A4")]
        public string CeldaFechaPlanillas {
            get {
                return ((string)(this["CeldaFechaPlanillas"]));
            }
            set {
                this["CeldaFechaPlanillas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G4")]
        public string CeldaTulaPlanillas {
            get {
                return ((string)(this["CeldaTulaPlanillas"]));
            }
            set {
                this["CeldaTulaPlanillas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I4")]
        public string CeldaManifiestoPlanillas {
            get {
                return ((string)(this["CeldaManifiestoPlanillas"]));
            }
            set {
                this["CeldaManifiestoPlanillas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SolicitudCodigoApertura {
            get {
                return ((global::System.Drawing.Color)(this["SolicitudCodigoApertura"]));
            }
            set {
                this["SolicitudCodigoApertura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color EsperaCodigoCierre {
            get {
                return ((global::System.Drawing.Color)(this["EsperaCodigoCierre"]));
            }
            set {
                this["EsperaCodigoCierre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color CodigoCierreRecibido {
            get {
                return ((global::System.Drawing.Color)(this["CodigoCierreRecibido"]));
            }
            set {
                this["CodigoCierreRecibido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C4")]
        public string CeldaIDBAC {
            get {
                return ((string)(this["CeldaIDBAC"]));
            }
            set {
                this["CeldaIDBAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D4")]
        public string CeldaTipoPunto {
            get {
                return ((string)(this["CeldaTipoPunto"]));
            }
            set {
                this["CeldaTipoPunto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I4")]
        public string CeldaManifiesto {
            get {
                return ((string)(this["CeldaManifiesto"]));
            }
            set {
                this["CeldaManifiesto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P4")]
        public string CeldaTarifa {
            get {
                return ((string)(this["CeldaTarifa"]));
            }
            set {
                this["CeldaTarifa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q4")]
        public string CeldaRecargo {
            get {
                return ((string)(this["CeldaRecargo"]));
            }
            set {
                this["CeldaRecargo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R4")]
        public string CeldaTotalFacturar {
            get {
                return ((string)(this["CeldaTotalFacturar"]));
            }
            set {
                this["CeldaTotalFacturar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A4")]
        public string CeldaFechaFacturacion {
            get {
                return ((string)(this["CeldaFechaFacturacion"]));
            }
            set {
                this["CeldaFechaFacturacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F7")]
        public string CeldaPrimeraDenominacionColonesNiquel {
            get {
                return ((string)(this["CeldaPrimeraDenominacionColonesNiquel"]));
            }
            set {
                this["CeldaPrimeraDenominacionColonesNiquel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q7")]
        public string CeldaSegundaDenominacionColonesNiquel {
            get {
                return ((string)(this["CeldaSegundaDenominacionColonesNiquel"]));
            }
            set {
                this["CeldaSegundaDenominacionColonesNiquel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R7")]
        public string CeldaPrimeraDenominacionDolaresNiquel {
            get {
                return ((string)(this["CeldaPrimeraDenominacionDolaresNiquel"]));
            }
            set {
                this["CeldaPrimeraDenominacionDolaresNiquel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W7")]
        public string CeldaSegundaDenominacionDolaresNiquel {
            get {
                return ((string)(this["CeldaSegundaDenominacionDolaresNiquel"]));
            }
            set {
                this["CeldaSegundaDenominacionDolaresNiquel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B8")]
        public string CeldaClienteNiquel {
            get {
                return ((string)(this["CeldaClienteNiquel"]));
            }
            set {
                this["CeldaClienteNiquel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G4")]
        public string CeldaFechaNiquel {
            get {
                return ((string)(this["CeldaFechaNiquel"]));
            }
            set {
                this["CeldaFechaNiquel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E8")]
        public string CeldaTransportadoraNiquel {
            get {
                return ((string)(this["CeldaTransportadoraNiquel"]));
            }
            set {
                this["CeldaTransportadoraNiquel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C4")]
        public string CeldaIDBacs {
            get {
                return ((string)(this["CeldaIDBacs"]));
            }
            set {
                this["CeldaIDBacs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D4")]
        public string CeldaPuntoVenta {
            get {
                return ((string)(this["CeldaPuntoVenta"]));
            }
            set {
                this["CeldaPuntoVenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R4")]
        public string CeldaTotal {
            get {
                return ((string)(this["CeldaTotal"]));
            }
            set {
                this["CeldaTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J4")]
        public string CeldaMontoPlanillas {
            get {
                return ((string)(this["CeldaMontoPlanillas"]));
            }
            set {
                this["CeldaMontoPlanillas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H4")]
        public string CeldaMontoTula {
            get {
                return ((string)(this["CeldaMontoTula"]));
            }
            set {
                this["CeldaMontoTula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G4")]
        public string CeldaTulaFacturacion {
            get {
                return ((string)(this["CeldaTulaFacturacion"]));
            }
            set {
                this["CeldaTulaFacturacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A2")]
        public string CeldaCodigoCompass {
            get {
                return ((string)(this["CeldaCodigoCompass"]));
            }
            set {
                this["CeldaCodigoCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2")]
        public string CeldaCuentaCompass {
            get {
                return ((string)(this["CeldaCuentaCompass"]));
            }
            set {
                this["CeldaCuentaCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E2")]
        public string CeldaMontoCompass {
            get {
                return ((string)(this["CeldaMontoCompass"]));
            }
            set {
                this["CeldaMontoCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public string CeldaReferenciaCompass {
            get {
                return ((string)(this["CeldaReferenciaCompass"]));
            }
            set {
                this["CeldaReferenciaCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G2")]
        public string CeldaPuntoVentaCompass {
            get {
                return ((string)(this["CeldaPuntoVentaCompass"]));
            }
            set {
                this["CeldaPuntoVentaCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I2")]
        public string CeldaIdentificacionCompass {
            get {
                return ((string)(this["CeldaIdentificacionCompass"]));
            }
            set {
                this["CeldaIdentificacionCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K2")]
        public string CeldaDepositoCompass {
            get {
                return ((string)(this["CeldaDepositoCompass"]));
            }
            set {
                this["CeldaDepositoCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L2")]
        public string CeldaManifiestoCompass {
            get {
                return ((string)(this["CeldaManifiestoCompass"]));
            }
            set {
                this["CeldaManifiestoCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M2")]
        public string CeldaClienteCompass {
            get {
                return ((string)(this["CeldaClienteCompass"]));
            }
            set {
                this["CeldaClienteCompass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A9")]
        public string CeldaCodigoTransportadora {
            get {
                return ((string)(this["CeldaCodigoTransportadora"]));
            }
            set {
                this["CeldaCodigoTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B9")]
        public string CeldaCuentaTransportadora {
            get {
                return ((string)(this["CeldaCuentaTransportadora"]));
            }
            set {
                this["CeldaCuentaTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E9")]
        public string CeldaMontoTransportadora {
            get {
                return ((string)(this["CeldaMontoTransportadora"]));
            }
            set {
                this["CeldaMontoTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F9")]
        public string CeldaReferenciaTransportadora {
            get {
                return ((string)(this["CeldaReferenciaTransportadora"]));
            }
            set {
                this["CeldaReferenciaTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J9")]
        public string CeldaPuntoVentaTransportadora {
            get {
                return ((string)(this["CeldaPuntoVentaTransportadora"]));
            }
            set {
                this["CeldaPuntoVentaTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I9")]
        public string CeldaIdentificacionTransportadora {
            get {
                return ((string)(this["CeldaIdentificacionTransportadora"]));
            }
            set {
                this["CeldaIdentificacionTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M9")]
        public string CeldaDepositoTransportadora {
            get {
                return ((string)(this["CeldaDepositoTransportadora"]));
            }
            set {
                this["CeldaDepositoTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K9")]
        public string CeldaManifiestoTransportadora {
            get {
                return ((string)(this["CeldaManifiestoTransportadora"]));
            }
            set {
                this["CeldaManifiestoTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A6")]
        public string CeldaFechaTarifaEnvio {
            get {
                return ((string)(this["CeldaFechaTarifaEnvio"]));
            }
            set {
                this["CeldaFechaTarifaEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B6")]
        public string CeldaIDPedidoEnvio {
            get {
                return ((string)(this["CeldaIDPedidoEnvio"]));
            }
            set {
                this["CeldaIDPedidoEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C6")]
        public string CeldaIDBACEnvio {
            get {
                return ((string)(this["CeldaIDBACEnvio"]));
            }
            set {
                this["CeldaIDBACEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D6")]
        public string CeldaTipoClienteEnvio {
            get {
                return ((string)(this["CeldaTipoClienteEnvio"]));
            }
            set {
                this["CeldaTipoClienteEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G6")]
        public string CeldaTipoServicioEnvio {
            get {
                return ((string)(this["CeldaTipoServicioEnvio"]));
            }
            set {
                this["CeldaTipoServicioEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H6")]
        public string CeldaPlanillaEnvio {
            get {
                return ((string)(this["CeldaPlanillaEnvio"]));
            }
            set {
                this["CeldaPlanillaEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I6")]
        public string CeldaMontoEnvio {
            get {
                return ((string)(this["CeldaMontoEnvio"]));
            }
            set {
                this["CeldaMontoEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J6")]
        public string CeldaMontoExcedenteEnvio {
            get {
                return ((string)(this["CeldaMontoExcedenteEnvio"]));
            }
            set {
                this["CeldaMontoExcedenteEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K6")]
        public string CeldaTipoCambioEnvio {
            get {
                return ((string)(this["CeldaTipoCambioEnvio"]));
            }
            set {
                this["CeldaTipoCambioEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L6")]
        public string CeldaTarifaNiquelEnvio {
            get {
                return ((string)(this["CeldaTarifaNiquelEnvio"]));
            }
            set {
                this["CeldaTarifaNiquelEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M6")]
        public string CeldaVisitaCompartidaEnvio {
            get {
                return ((string)(this["CeldaVisitaCompartidaEnvio"]));
            }
            set {
                this["CeldaVisitaCompartidaEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N6")]
        public string CeldaVisitaNocturnaEnvio {
            get {
                return ((string)(this["CeldaVisitaNocturnaEnvio"]));
            }
            set {
                this["CeldaVisitaNocturnaEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O6")]
        public string CeldaRecargoEnvio {
            get {
                return ((string)(this["CeldaRecargoEnvio"]));
            }
            set {
                this["CeldaRecargoEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P6")]
        public string CeldaTotalEnvio {
            get {
                return ((string)(this["CeldaTotalEnvio"]));
            }
            set {
                this["CeldaTotalEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H1")]
        public string CeldaTransportadoraEnvio {
            get {
                return ((string)(this["CeldaTransportadoraEnvio"]));
            }
            set {
                this["CeldaTransportadoraEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A2")]
        public string CeldaCartuchoM {
            get {
                return ((string)(this["CeldaCartuchoM"]));
            }
            set {
                this["CeldaCartuchoM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2")]
        public string CeldaTipoM {
            get {
                return ((string)(this["CeldaTipoM"]));
            }
            set {
                this["CeldaTipoM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C2")]
        public string CeldaEstadoM {
            get {
                return ((string)(this["CeldaEstadoM"]));
            }
            set {
                this["CeldaEstadoM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D2")]
        public string CeldaTransportadoraM {
            get {
                return ((string)(this["CeldaTransportadoraM"]));
            }
            set {
                this["CeldaTransportadoraM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E2")]
        public string CeldaProveedorM {
            get {
                return ((string)(this["CeldaProveedorM"]));
            }
            set {
                this["CeldaProveedorM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDAP://CRI.CORP.REDBAC.COM:389/DC=CRI,DC=CORP,DC=REDBAC,DC=com")]
        public string LPAD {
            get {
                return ((string)(this["LPAD"]));
            }
            set {
                this["LPAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.122.3.127,3033")]
        public string BDSwitch {
            get {
                return ((string)(this["BDSwitch"]));
            }
            set {
                this["BDSwitch"] = value;
            }
        }
    }
}
